name: Generate terraform docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
        contents: 'read'
        id-token: 'write'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Render terraform docs inside the TF-docs.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .
        output-file: TF-docs.md
        output-method: replace
        config-file: .terraform-docs.yml
        git-push: "true"  # This will commit and push the changes